from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0001_initial"),
    ]

    operations = [

        migrations.CreateModel(
            name="MarketAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_used",
                    models.CharField(
                        blank=True,
                        max_length=500,
                    ),
                ),
                (
                    "open_source_competitors",
                    models.PositiveIntegerField(
                        default=0
                    ),
                ),
                (
                    "strong_open_source_competitors",
                    models.PositiveIntegerField(
                        default=0
                    ),
                ),
                (
                    "saturation_score",
                    models.PositiveSmallIntegerField(
                        default=0
                    ),
                ),
                (
                    "saturation_level",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                            ("very_high", "Muito alta"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "top_competitor_name",
                    models.CharField(
                        blank=True,
                        max_length=520,
                    ),
                ),
                (
                    "top_competitor_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                    ),
                ),
                (
                    "top_competitor_stars",
                    models.PositiveIntegerField(
                        default=0
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True
                    ),
                ),
                (
                    "researched_at",
                    models.DateTimeField(
                        auto_now=True
                    ),
                ),
                (
                    "opportunity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_analysis",
                        to="opportunities.opportunity",
                    ),
                ),
            ],
        ),

        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github_id",
                    models.BigIntegerField(),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=520
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=1000
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        max_length=120,
                    ),
                ),
                (
                    "stars",
                    models.PositiveIntegerField(
                        default=0
                    ),
                ),
                (
                    "forks",
                    models.PositiveIntegerField(
                        default=0
                    ),
                ),
                (
                    "open_issues",
                    models.PositiveIntegerField(
                        default=0
                    ),
                ),
                (
                    "license_spdx",
                    models.CharField(
                        blank=True,
                        max_length=80,
                    ),
                ),
                (
                    "relevance_score",
                    models.PositiveSmallIntegerField(
                        default=0
                    ),
                ),
                (
                    "is_strong",
                    models.BooleanField(
                        default=False
                    ),
                ),
                (
                    "pushed_at_github",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="opportunities.opportunity",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-relevance_score",
                    "-stars",
                ],
            },
        ),

        migrations.AddConstraint(
            model_name="competitor",
            constraint=models.UniqueConstraint(
                fields=(
                    "opportunity",
                    "github_id",
                ),
                name="unique_opportunity_competitor",
            ),
        ),

        migrations.AddIndex(
            model_name="competitor",
            index=models.Index(
                fields=[
                    "opportunity",
                    "-relevance_score",
                ],
                name="opportuniti_opportu_market_idx",
            ),
        ),

        migrations.AddIndex(
            model_name="competitor",
            index=models.Index(
                fields=["-stars"],
                name="opportuniti_stars_market_idx",
            ),
        ),
    ]
